id: P009381
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 19:36:07.302163
source_metadata:
  id: bdr:W29186
  title: གསུང་འབུམ། ཡེ་ཤེས་རྒྱ་མཚོ
  author: ''
  volumes:
    79d5b48af76342adb62b0130755662ed:
      image_group_id: I00EGS1017108
      title: ''
      volume_number: 1
      total_pages: 620
      base_file: v001.txt
    8ed84e94252c4e35b034396d665ef40c:
      image_group_id: I00EGS1017109
      title: ''
      volume_number: 2
      total_pages: 694
      base_file: v002.txt
    0128f630a85e47d28b98fb7585207ec8:
      image_group_id: I00EGS1017110
      title: ''
      volume_number: 3
      total_pages: 614
      base_file: v003.txt
    cfae408b5252459e8518d63f113b546a:
      image_group_id: I00EGS1017111
      title: ''
      volume_number: 4
      total_pages: 622
      base_file: v004.txt
    9767fbe8fee8442d9ac5afc9aa62eb72:
      image_group_id: I00EGS1017112
      title: ''
      volume_number: 5
      total_pages: 646
      base_file: v005.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
