id: I17A1A1CA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T07:48:14+00:00'
last_modified: '2022-06-08T10:36:37.547975+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29186
  title: གསུང་འབུམ། ཡེ་ཤེས་རྒྱ་མཚོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FB2E:
      image_group_id: I00EGS1017108
      title: ''
      total_pages: 620
      order: 1
      base_file: FB2E.txt
    7D50:
      image_group_id: I00EGS1017109
      title: ''
      total_pages: 694
      order: 2
      base_file: 7D50.txt
    8D47:
      image_group_id: I00EGS1017110
      title: ''
      total_pages: 614
      order: 3
      base_file: 8D47.txt
    49E2:
      image_group_id: I00EGS1017111
      title: ''
      total_pages: 622
      order: 4
      base_file: 49E2.txt
    D3F7:
      image_group_id: I00EGS1017112
      title: ''
      total_pages: 646
      order: 5
      base_file: D3F7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
