id: I17A1A1CA
legacy_id: P009381
ocr_import_info:
  bdrc_scan_id: W29186
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T07:43:36'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T09:54:52.891172+00:00'
last_modified: 2022-09-02 17:58:21.087458
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29186
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW29186
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཡེ་ཤེས་རྒྱ་མཚོ།
  author: ཡེ་ཤེས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9561053344247933
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I00EGS1017111:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017111
      total_pages: 622
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I00EGS1017111.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9541295689834141
    legacy_id: v004
  I00EGS1017109:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017109
      total_pages: 694
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I00EGS1017109.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9629800083512937
    legacy_id: v002
  I00EGS1017110:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017110
      total_pages: 614
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I00EGS1017110.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9489738301112773
    legacy_id: v003
  I00EGS1017112:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017112
      total_pages: 646
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I00EGS1017112.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9570453153309111
    legacy_id: v005
  I00EGS1017108:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017108
      total_pages: 620
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00EGS1017108.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9564241091458177
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
